name: Zig package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0-dev.2261+fbcb00fbb
      
      - name: Build
        run: zig build -v
      
      - name: Test
        run: zig build test --summary all
